language: java
install:
  - git clone https://github.com/masterlemmi/commons.git
  - cd commons && ./gradlew build publishToMavenLocal

jdk:
  - oraclejdk8

services:
  - docker

script:
  - ./gradlew build
  - docker build -t $DOCKER_UN/hobbies-svc .
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_UN" --password-stdin
  - docker push $DOCKER_UN/hobbies-svc
