INSERT INTO LANGUAGE (ID, NAME) VALUES (1, 'Ilocano');
INSERT INTO LANGUAGE (ID, NAME) VALUES (2, 'Japanese');
INSERT INTO LANGUAGE (ID, NAME) VALUES (3, 'Cebuano');
INSERT INTO LANGUAGE (ID, NAME) VALUES (4, 'French');
INSERT INTO LANGUAGE (ID, NAME) VALUES (5, 'Chinese');

